version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'monthly'

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "terraform/"
    schedule:
      interval: "monthly"

  # Workaround till https://github.com/dependabot/dependabot-core/issues/2178 is fixed
  - package-ecosystem: "terraform"
    directory: "terraform/environments/prd"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "terraform/modules/analytics/application_insights"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "terraform/modules/analytics/log_analytics_workspace"
    schedule:
      interval: "monthly"
