name: 'Recognize Internal Security Assistant'
description: 'Given an URL, this action creates a security report with some basic server settings.'
inputs:
  urls:
    description: 'List of URLs'
    required: true
  excluded:
    description: 'Comma separated list of excluded rules'
    required: false
    default: ''
  github-app-id:
    description: 'GitHub App ID'
    required: true
  github-app-installation-id:
    description: 'GitHub App Installation ID'
    required: true
  github-app-private-key:
    description: 'GitHub App Private Key'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
