name: 'Development'
on:
  push:
    branches:
      - feature/TD-553-security-reports-dashboards

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: recognizegroup/recognize-security-report-action@feature/TD-553-security-reports-dashboards
        with:
          urls: https://recognize.nl
          token: ${{ github.token }}
