name: 'Build & Test action'
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all

  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          urls: https://recognize.nl
